#include "WWDG.h"

void init_wwdg(void){
	SET_BIT(RCC->APBENR1,RCC_APBENR1_WWDGEN);
	SET_WWDG_DIV(WWDG_DIV4);
	MODIFY_REG(WWDG->CR,WWDG_CR_T,UPPER_VALUE<<WWDG_CR_T_Pos);
	MODIFY_REG(WWDG->CFR,WWDG_CFR_W,WINDOW_VALUE<<WWDG_CFR_W_Pos);
	ENABLE_WWDG;
}

void WWDG_reload(void){
 MODIFY_REG(WWDG->CR, WWDG_CR_T, UPPER_VALUE << WWDG_CR_T_Pos);
}